services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://c00rd1n4d0r4:ToJ1@GO1_o25x@db:5432/rt_coordinadora
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15.6
    environment:
      POSTGRES_DB: rt_coordinadora
      POSTGRES_USER: c00rd1n4d0r4
      POSTGRES_PASSWORD: ToJ1@GO1_o25x
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./models:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
