version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: node app.js
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: eventplatformdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
